# Put this file in `/home/yourusername/.config/fff.toml`.

# pdf_command_format forces a specific program and arguments for opening PDFs.
# The `page` argument is optional. For fulltext searches, it enables opening the PDF at the relevant page.
# Uncomment the example that corresponds to your preferred PDF reader, or write your own:
#
# pdf_command_format = ['evince', '--page-index={page}', '{file}']
# pdf_command_format = ['zathura', '--page={page}', '{file}']

# default_command_format specifies which generic file handler to use
# Uncomment the example that corresponds to your preferred handler, or write your own:
#
# default_command_format = ['xdg-open', '{file}']
# default_command_format = ['handlr', 'open', '{file}']
